# Generated by Django 4.1.7 on 2023-03-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bid_bidder_bid_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to='auctions.bid')),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='auctions.listing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
