# Generated by Django 4.1.7 on 2023-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time',
        ),
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
