# Generated by Django 4.1.7 on 2023-03-21 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_time_listing_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
