# Generated by Django 4.1.7 on 2023-03-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='datetime',
        ),
    ]
