# Generated by Django 4.1.7 on 2023-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
