# Generated by Django 4.1.7 on 2023-03-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
