# Generated by Django 4.1.7 on 2023-03-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_watchlist_item_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
    ]
