# Generated by Django 4.1.7 on 2023-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
